root_dir: "./results/image"
output: "result.png"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 301

dataset: random
batch_size: 1
width: 512
height: 512

model: image
initialization: random
learning_rate: 0.1
channels: 3

prior: sd
guidance_scale: 7.5

sampler: sds
linear_annealing: true
reduction: sum

logger: simple
log_interval: 20

background: solid
rgb: [0, 0, 0]