root_dir: "./results7/image_gen"
output: "result.png"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 500
batch_size: 1
dataset: random
background: black_white
model: image
prior: sd
sampler: dreamtime
logger: simple
use_view_dependent_prompt: false
guidance_scale: 7.5
reduction: sum