root_dir: "./results/image_df"
output: "result.pt"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 1000
batch_size: 1
dataset: random
background: black_white
model: image
prior: df
sampler: sds
logger: simple
use_view_dependent_prompt: false
guidance_scale: 7.5
reduction: sum
width: 64
height: 64