root_dir: "./results7/image_gen"
output: "result.png"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 301

dataset: random
batch_size: 1
width: 64
height: 64

model: latent_image

prior: sd
guidance_scale: 7.5

sampler: dreamtime
reduction: sum

logger: simple_latent
log_interval: 20

background: black_white