root_dir: "./results/gs_mv_ddim"
text_prompt: "a zoomed out DSLR photo of a baby dragon"
max_steps: 50
xyz_lr: 0.0005
scale_lr: 0.002
quat_lr: 0.001
opacity_lr: 0.12
feature_lr: 0.01
batch_size: 4
dataset: random_mv
background: nerf
model: gs
prior: mvdream
sampler: sds
linear_annealing: true
logger: self
height: 256
width: 256
guidance_scale: 7.5

recon_type: rgb
recon_steps: 40
initial_recon_steps: 200

refine_start_iter: 0
refine_stop_iter: 1
refine_every: 1
init_splats: 20000
max_splats: 40000