# Main Differences:
# max_steps: 300
# learning_rate: 0.01
# noise_sampler: sdi
# log_interval: 30
# recon_steps: 1
# use_closed_form: false

root_dir: "./results/image"
tag: image
output: "result.png"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 300

dataset: random
batch_size: 1
width: 64
height: 64

model: image
initialization: random
learning_rate: 0.01
channels: 4

prior: sd
guidance_scale: 7.5

time_sampler: linear_annealing
noise_sampler: sdi

logger: simple
log_interval: 30

background: solid
rgb: [0, 0, 0, 0]

recon_steps: 1
recon_type: latent
use_closed_form: false