# Main Differences:
# max_steps: 50
# learning_rate: 0.1 (Optional)
# noise_sampler: ddim
# log_interval: 1
# recon_steps: 400 (Optional)
# use_closed_form: true

root_dir: "./results/image"
tag: image
output: "result.png"
text_prompt: "Panoramic view of Singapore skyscrapers at night."
max_steps: 50

dataset: random
batch_size: 1
width: 64
height: 64

model: image
initialization: random
learning_rate: 0.01
channels: 4

prior: sd
guidance_scale: 7.5

time_sampler: linear_annealing
noise_sampler: ddim

logger: simple
log_interval: 10

background: solid
rgb: [0, 0, 0, 0]

recon_steps: 1
recon_type: latent
use_closed_form: true 