root_dir: "./results/img_wide"
text_prompt: "Skyline of New York City"
tag: wide_image
max_steps: 300

dataset: image_wide
height: 64
width: 64
yscale: 1
xscale: 4
batch_size: 15

model: image_wide
learning_rate: 1.5
channels: 4
disable_debug: False  # True to make it faster

prior: sd
guidance_scale: 7.5

background: solid
rgb: [0, 0, 0, 0]

timesampler: linear_annealing
noisesampler: sds

logger: simple
log_interval: 10

recon_steps: 1
recon_type: latent
use_closed_form: false