root_dir: "./results/img_wide"
text_prompt: "Skyline of New York City"
tag: wide_image 
max_steps: 300 # Use 300 steps for optimization (30 for closed form)

dataset: image_wide 
height: 64
width: 64
xscale: 4
yscale: 1
batch_size: 15

model: image_wide
learning_rate: 0.02 # (0.01 * batch_size)
channels: 4
disable_debug: False  # True to make it faster

prior: sd
guidance_scale: 7.5

background: solid
rgb: [0, 0, 0, 0]

time_sampler: linear_annealing
noise_sampler: sdi

logger: simple
log_interval: 1

recon_steps: 1 # No closed form optimization
recon_type: latent # Optimization space 
use_closed_form: false 