root_dir: "./results/img_wide"
text_prompt: "Skyline of New York City"
tag: wide_image
max_steps: 20

dataset: alternate_image_wide
height: 64
width: 64
yscale: 1
xscale: 4
batch_size: 7

model: image_wide
learning_rate: 2.0
channels: 4
disable_debug: False  # True to make it faster

prior: sd
guidance_scale: 7.5

background: solid
rgb: [0, 0, 0, 0]

time_sampler: linear_annealing
noise_sampler: sds

logger: self
log_interval: 1

recon_steps: 400
recon_type: latent
use_closed_form: true