root_dir: "./results/mesh"
tag: mesh
text_prompt: "a DSLR photo of face of Kratos, god of war, best quality, high quality, extremely detailed, good geometry"
max_steps: 200
batch_size: 1

# dataset: camera
dataset: random
height: 512
width: 512
convention: OpenGL
dist_range: [2.3, 2.5]
asim_range: [0, 360]
elev_range: [-5, 20]
up_vec: y
# dists: [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]
# elevs: [0, 10, 0, 10, 0, 10, 0, 10]
# azims: [0, 45, 90, 135, 180, 225, 270, 315]
# dists: [2.2]
# elevs: [0]
# azims: [45]
fov: 60

background: solid
rgb: [0.25, 0.25, 0.25]

model: mesh
mesh_path: "/home/aaaaa/repo/distill/_previous_results_bin/extra_data/face.obj"
texture_size: 1024
mesh_scale: 1.0
initialization: "gray"
learning_rate: 0.05
disable_debug: False # Faster 

prior: controlnet
guidance_scale: 15.5

time_sampler: linear_annealing
noise_sampler: sds

use_ode: true
ode_steps: 30

logger: simple 
log_interval: 1

recon_steps: 1
recon_type: rgb  # optim=1: latent, optim=inf: rgb
use_closed_form: true
use_selection: true