root_dir: "./results/panorama"
tag: panorama
text_prompt: "Graffiti-covered alleyway with street art murals"
max_steps: 25
use_encoder_decoder: False 

dataset: camera
height: 512
width: 512
batch_size: 4
fov: 110
dists: [2.5, 2.5, 2.5, 2.5]
elevs: [25, 25, 25, 25]
azims: [0, 90, 180, 270]

model: panorama
learning_rate: 0.07
pano_height: 2048
pano_width: 4096
channels: 3
disable_debug: False # Faster
init_img_path: /home/aaaaa/repo/distill/_engineering2/Graffiti-covered_alleyway_with_street_art_murals_400/panorama/20240912_182630/_output/000.png
initialization: image

prior: sd
guidance_scale: 1.0

background: solid
rgb: [0, 0, 0]

time_sampler: good
t_max: 900
t_min: 270
noise_sampler: sds

use_ode: true
ode_steps: 50

logger: self 
log_interval: 1

recon_steps: 1
recon_type: rgb  # optim=1: latent, optim=inf: rgb
use_closed_form: true


# use_closed_form=true & recon_type=rgb & max_steps = 30
# use_closed_form=false & recon_type=latent & max_steps = 300

# noise_sampler: ddim, sds, sdi

# use_ode: true, false