root_dir: "./results/panorama"
tag: panorama
text_prompt: "Interior of an old looking library"
max_steps: 300
use_encoder_decoder: False 

dataset: random_mv
height: 512
width: 512
batch_size: 10
fov: 72
dist_range: [1, 1]
elev_range: [0, 0]
azim_range: [0, 0]

model: panorama
learning_rate: 0.1
channels: 3
disable_debug: True # Faster 

prior: sd
guidance_scale: 7.5

background: solid
rgb: [0, 0, 0]

timesampler: linear_annealing
noisesampler: sds

logger: simple 
log_interval: 10

recon_steps: 1
recon_type: rgb
use_closed_form: false