root_dir: "./results/gs_mv"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 1000
batch_size: 4
dataset: random_mv
background: black_white
model: gs
prior: mvdream
sampler: dreamtime
logger: procedure
height: 256
width: 256
refine_start_iter: 50
refine_stop_iter: 30000
refine_every: 100