root_dir: "./results/ngp"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 2000

dataset: random
height: 512
width: 512
convention: RUF
batch_size: 1
dist_range: [1.5, 1.5]

model: ngp

prior: sd
guidance_scale: 7.5

background: black_white

logger: self
log_interval: 100

sampler: sds
linear_annealing: true