root_dir: "./results/ngp_mv"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 2000

dataset: random_mv
height: 256
width: 256
convention: RUF
batch_size: 4
dist_range: [1.5, 1.8]

model: ngp

prior: mvdream
guidance_scale: 7.5

background: black_white

logger: self
log_interval: 100

sampler: sds
linear_annealing: true