root_dir: "./results/panorama"
tag: panorama
# text_prompt: "Steampunk airship, navigating cloudy skies, gears turning, propellers whirring."
# angle_prompts: Dict[int, str] = field(
#     default_factory=lambda: {
#         "front": "a room",
#         "right": "a room",
#         "back": "a room",
#         "left": "a room",
#         "top": "a ceiling",
#         "bottom": "a floor",
#     }
# )
# In YAML style
angle_prompts: 
  front: "a mountain view"
  right: "a mountain view"
  back: "a mountain view"
  left: "a mountain view"
  top: "a ceiling of a room"
  bottom: "a floor of a room"
max_steps: 30 # In ODE -> 25
use_encoder_decoder: False 
warmup_steps: 2

dataset: alternate_camera
height: 512
width: 512
batch_size: 4
fov: 72
# dists: [
#   2.0, 2.0, 2.0, 2.0,
#   2.0, 2.0, 2.0, 2.0,
#   2.0, 2.0, 2.0, 2.0,
#   2.0, 2.0, 2.0, 2.0,
#   2.0, 2.0, 2.0, 2.0,
#   2.0, 2.0, 2.0, 2.0
# ]
dists: [
  2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0
]
# elevs: [
#   0, 0, 0, 0,       # A right
#   0, 0, 0, 0,       # A wrong
#   0, 90, 0, -90,    # B right
#   -45, 45, -45, 45, # B wrong
#   0, 90, 0, -90,    # C right
#   -45, 45, -45, 45  # C wrong
# ]
# azims: [
#   0, 90, 180, 270,    # A right
#   45, 135, 225, 315,  # A wrong
#   0, 0, 180, 180,     # B right
#   0, 0, 180, 180,     # B wrong
#   90, 90, 270, 270,   # C right
#   90, 90, 270, 270    # C wrong
# ]
# elevs: [
#   0, 0, 0, 0,       # A right
#   -45, 45, -45, 45, # B wrong
#   0, 90, 0, -90,    # C right
#   0, 0, 0, 0,       # A wrong
#   0, 90, 0, -90,    # B right
#   -45, 45, -45, 45  # C wrong
# ]
# azims: [
#   0, 90, 180, 270,    # A right
#   0, 0, 180, 180,     # B wrong
#   90, 90, 270, 270,   # C right
#   45, 135, 225, 315,  # A wrong
#   0, 0, 180, 180,     # B right
#   90, 90, 270, 270    # C wrong
# ]
elevs: [
  0, 0, 0, 0,
  0, 0, 0, 0
]
azims: [
  0, 90, 180, 270,
  45, 135, 225, 315
]

model: cubemap
channels: 3
disable_debug: False

prior: cubemap_sd
guidance_scale: 7.5

background: solid
rgb: [0, 0, 0]

time_sampler: linear_annealing 
t_max: 999 # In Tweedie -> 999
t_min: 270 # In Tweedie -> 0
seam_removal_steps: 4 # Use only in ODE cases 
noise_sampler: sds

use_ode: true
ode_steps: 30

logger: self 
log_interval: 1

recon_steps: 1
recon_type: rgb
use_closed_form: true
learning_rate: 0.0
loss_scale: 1.0
