root_dir: "./results/panorama"
tag: panorama
text_prompt: "Interior of an old looking library"
max_steps: 25 # In ODE -> 25
use_encoder_decoder: False 

dataset: alternate_mv
height: 512
width: 512
batch_size: 10
fov: 72
dist_range: [1, 1]
elev_range: [0, 0]
azim_range: [0, 360]

model: panorama
pano_height: 2048
pano_width: 4096
channels: 3
disable_debug: False

prior: sd
guidance_scale: 7.5

background: solid
rgb: [0, 0, 0]

time_sampler: linear_annealing 
t_max: 900 # In Tweedie -> 999
t_min: 270 # In Tweedie -> 0
seam_removal_steps: 2 # Use only in ODE cases 
noise_sampler: sds

use_ode: true
ode_steps: 50

logger: self 
log_interval: 5

recon_steps: 1
recon_type: rgb
use_closed_form: true
learning_rate: 0.0
loss_scale: 1.0
