root_dir: "./results/panorama"
tag: panorama
text_prompt: "Interior of an old looking library"
max_steps: 2000
use_encoder_decoder: False 

dataset: random
height: 64 # 64 for latent / 512 for rgb
width: 64 # 64 for latent / 512 for rgb
batch_size: 10
fov: 72
dist_range: [1, 1]
elev_range: [0, 0]
azim_range: [0, 360]

model: panorama
pano_height: 1024 # 1024 for latent / 2048 for rgb
pano_width: 2048 # 2048 for latent / 4096 for rgb
channels: 4 # 4 for latent / 3 for rgb
disable_debug: False

prior: sd
guidance_scale: 7.5

background: solid
rgb: [0, 0, 0, 0] # [0, 0, 0, 0] for latent / [0, 0, 0] for rgb

time_sampler: sds
t_max: 980
t_min: 100
seam_removal_steps: 0 
noise_sampler: ism

use_ode: false
ode_steps: 50

logger: self 
log_interval: 200

recon_steps: 1
recon_type: latent  # optim=1: latent, optim=inf: rgb
use_closed_form: false
learning_rate: 0.03 # 0.1 SDS / 0.01 SDI 
loss_scale: 1.0