root_dir: "./results/sphere"
tag: sphere
text_prompt: "A sweet candy texture"
max_steps: 12 # In ODE -> 25
use_encoder_decoder: False 
warmup_steps: 1

dataset: quat
height: 512
width: 512
batch_size: 6
fov: 90
dists: [
  2.0, 2.0, 2.0, 2.0, 2.0, 2.0
]
elevs: [
  0, 0, 0, 0, 90, -90
]
azims: [
  0, 90, 180, 270, 0, 0
]

model: panorama
pano_height: 2048
pano_width: 4096
channels: 3
disable_debug: False
gt_azim: 0
gt_elev: 0
seam_removal_mode: both
mode: sphere

prior: sd
guidance_scale: 8.5
mixed_precision: True

background: solid
rgb: [0, 0, 0]

time_sampler: linear_annealing 
t_max: 999 # In Tweedie -> 999
t_min: 400 # In Tweedie -> 0
seam_removal_steps: 4 # Use only in ODE cases 
noise_sampler: sds

use_ode: true
ode_steps: 75

logger: self 
log_interval: 1

recon_steps: 1
recon_type: rgb
use_closed_form: true
learning_rate: 0.0
loss_scale: 1.0
