root_dir: ./results/
tag: torus
text_prompt: "A sweet candy texture"

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 12
warmup_steps: 1

use_ode: true
ode_steps: 50
seam_removal_steps: 4

use_closed_form: true
recon_type: rgb
recon_steps: 1

disable_debug: False

#===============================================================================
# Dataset
#===============================================================================
dataset: torus
height: 512
width: 512
batch_size: 6
fov: 180
dists: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
elevs: [90, 0, 90, 0, -90, -90]
azims: [0, 90, 180, 270, 0, 180]

#===============================================================================
# Background
#===============================================================================
background: solid
rgb: [0, 0, 0]

#===============================================================================
# Model
#===============================================================================
model: panorama
mode: torus
pano_height: 1024
pano_width: 3072
channels: 3
seam_removal_mode: both

#===============================================================================
# Prior
#===============================================================================
prior: sd
guidance_scale: 8.5
mixed_precision: True

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: linear_annealing 
t_max: 999
t_min: 400

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: sds

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1