root_dir: "./results/latent_mesh_sd"
text_prompt: "a DSLR photo of a crow, photorealistic"
max_steps: 1000
batch_size: 1

dataset: random
height: 64
width: 64
convention: Pytorch3D
up_vec: y
dist_range: [2.0, 2.0]
elev_range: [15, 15]
azim_range: [135, 135]

background: latent_solid
# tuple of 1, 1, 1
rgb: [1, 1, 1]

model: mesh
mesh_path: "tmp_mesh.obj"
texture_size: 128
mesh_scale: 1.0
sampling_mode: nearest
initialization: random
learning_rate: 0.01
channels: 4

prior: sd

sampler: dreamtime

logger: simple_latent
log_interval: 10