root_dir: "./results7/mvdream_image_gen"
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"
max_steps: 500
batch_size: 4
dataset: random_mv
azim_range: [0, 0]
background: black_white
model: mvdream_image
prior: mvdream
sampler: dreamtime
logger: procedure
height: 256
width: 256