root_dir: ./results/
tag: image_sds
text_prompt: "A DSLR photo of a baby bunny sitting on top of a stack of pancakes"

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 1000
warmup_steps: 0

use_ode: false
ode_steps: -1
seam_removal_steps: 0

use_closed_form: false
recon_type: latent
recon_steps: 1

disable_debug: False

#===============================================================================
# Dataset
#===============================================================================
dataset: random
batch_size: 1
width: 64
height: 64

#===============================================================================
# Background
#===============================================================================
background: solid
rgb: [0, 0, 0, 0]

#===============================================================================
# Model
#===============================================================================
model: image
initialization: random
learning_rate: 0.01
channels: 4

#===============================================================================
# Prior
#===============================================================================
prior: sd
guidance_scale: 7.5
mixed_precision: false

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: sds 
t_max: 999
t_min: 0

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: sds

#===============================================================================
# Logger
#===============================================================================
logger: simple_latent_preview
log_interval: 10
save_video: True