root_dir: ./results
tag: mvdream_3dgs_fast
text_prompt: "a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes, no background"

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 500
warmup_steps: 0

use_ode: false
ode_steps: -1
seam_removal_steps: 0

use_closed_form: false
recon_type: latent
recon_steps: 1

disable_debug: False

#===============================================================================
# Dataset
#===============================================================================
dataset: random_mv
batch_size: 4
height: 256
width: 256
convention: RDF
up_vec: z
fov: 72
dist_range: [1.8, 2.2]
elev_range: [-5, 40]
azim_range: [0, 360]

#===============================================================================
# Background
#===============================================================================
background: black_white

#===============================================================================
# Model
#===============================================================================
model: gs
xyz_lr: 0.0002
scale_lr: 0.008
quat_lr: 0.0005
opacity_lr: 0.04
feature_lr: 0.008
refine_every: 50
refine_start_iter: 50
refine_stop_iter: 30000

#===============================================================================
# Prior
#===============================================================================
prior: mvdream
guidance_scale: 7.5

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: linear_annealing 
t_max: 999
t_min: 200

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: sds

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 20