root_dir: ./results/
tag: stochsync_mesh
text_prompt: "Kratos bust, God of War, god of power, hyper-realistic and extremely detailed."

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 26
warmup_steps: 5

use_ode: true
ode_steps: 22
seam_removal_steps: 5

use_closed_form: true
recon_type: rgb
recon_steps: 1

disable_debug: False
try_fast_sampling: True

#===============================================================================
# Dataset
#===============================================================================
dataset: alternate_camera
batch_size: 3
height: 768
width: 768
convention: OpenGL
up_vec: y
fov: 60
dists: [
  2.0, 2.0, 2.0,
  2.0, 2.0, 2.0,
  2.0, 2.0, 2.0,
  2.0, 2.0, 2.0,
  2.0, 2.0, 2.0,
]
elevs: [
  0, 30, -15,
  0, 30, -15,
  0, 30, -15,
  0, 30, -15,
  0, 30, -15,
]
azims: [
  90.00, 210.00, 330.00,
  234.00, 354.00, 114.00,
  18.00, 138.00, 258.00,
  162.00, 282.00, 42.00,
  306.00, 66.00, 186.00
]

#===============================================================================
# Background
#===============================================================================
background: cache
rgb: [0.1, 0.1, 0.1]

#===============================================================================
# Model
#===============================================================================
model: mesh
mesh_path: "./data/mesh/face.obj"
texture_size: 2048
mesh_scale: 1.0
initialization: gray
learning_rate: 0.05
channels: 3
sampling_mode: linear
use_selection: true

#===============================================================================
# Prior
#===============================================================================
prior: sd2_depth
guidance_scale: 15.5
mixed_precision: true
use_view_dependent_prompt: true

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: linear_annealing 
t_max: 999
t_min: 270

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: sds

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 5