root_dir: ./results/
tag: image_inpainting
text_prompt: "A DSLR photo of a house with a red roof, photorealistic, masterpiece"

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 50
warmup_steps: 0

use_ode: true
ode_steps: 30
seam_removal_steps: 0
try_fast_sampling: true

use_closed_form: true
recon_type: latent
recon_steps: 1

disable_debug: False

#===============================================================================
# Dataset
#===============================================================================
dataset: random
batch_size: 1
width: 64
height: 64

#===============================================================================
# Background
#===============================================================================
background: solid
rgb: [0, 0, 0, 0]

#===============================================================================
# Model
#===============================================================================
model: image_inpainting
initialization: random
learning_rate: 0.01
channels: 4
gt_image_path: data/image_half.png

#===============================================================================
# Prior
#===============================================================================
prior: sd
guidance_scale: 7.5
mixed_precision: true

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: linear_annealing 
t_max: 999
t_min: 0

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: sds

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1