root_dir: ./results/
tag: stochsync_panorama
text_prompt: "Graffiti-covered alleyway on a sunny afternoon"

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 25
warmup_steps: 2

use_ode: true
ode_steps: 20
seam_removal_steps: 2

use_closed_form: true
recon_type: rgb
recon_steps: 1

disable_debug: False
try_fast_sampling: True

#===============================================================================
# Dataset
#===============================================================================
dataset: alternate_camera
batch_size: 5
height: 512
width: 512
fov: 72
dists: [
  1, 1, 1, 1, 1,
  1, 1, 1, 1, 1,
]
elevs: [
  0, 0, 0, 0, 0,
  0, 0, 0, 0, 0,
]
azims: [
  0, 72, 144, 216, 288,
  36, 108, 180, 252, 324,
]

#===============================================================================
# Background
#===============================================================================
background: solid
rgb: [0, 0, 0]

#===============================================================================
# Model
#===============================================================================
model: panorama
mode: panorama
pano_height: 2048
pano_width: 4096
channels: 3
seam_removal_mode: horizontal

#===============================================================================
# Prior
#===============================================================================
prior: sd
guidance_scale: 7.5
mixed_precision: true

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: linear_annealing 
t_max: 999
t_min: 270

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: sds

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1