root_dir: ./results/
tag: stochsync_panorama_upscale
text_prompt: "A vibrant urban alleyway filled with colorful graffiti, bold designs, and stylized lettering on wall, extremely detailed and realistic."
seed: 42

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 12
warmup_steps: 0

use_ode: true
ode_steps: 30
seam_removal_steps: 4

use_closed_form: true
recon_type: rgb
recon_steps: 1

disable_debug: False
try_fast_sampling: True

#===============================================================================
# Dataset
#===============================================================================
dataset: alternate_camera
batch_size: 15
height: 512
width: 512
fov: 36
dists: [
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
]
elevs: [
  0, 18, -18, 0, 18, -18, 0, 18, -18, 0, 18, -18, 0, 18, -18,
  0, 18, -18, 0, 18, -18, 0, 18, -18, 0, 18, -18, 0, 18, -18,
  0, 18, -18, 0, 18, -18, 0, 18, -18, 0, 18, -18, 0, 18, -18,
  0, 18, -18, 0, 18, -18, 0, 18, -18, 0, 18, -18, 0, 18, -18,
]
azims: [
  0, 36, 36, 72, 108, 108, 144, 180, 180, 216, 252, 252, 288, 324, 324,
  18, 54, 54, 90, 126, 126, 162, 198, 198, 234, 270, 270, 306, 342, 342,
  36, 72, 72, 108, 144, 144, 180, 216, 216, 252, 288, 288, 324, 0, 0,
  54, 90, 90, 126, 162, 162, 198, 234, 234, 270, 306, 306, 342, 18, 18,
]

#===============================================================================
# Background
#===============================================================================
background: solid
rgb: [0, 0, 0]

#===============================================================================
# Model
#===============================================================================
model: panorama
mode: panorama
pano_height: 4096
pano_width: 8192
channels: 3
seam_removal_mode: both
initialization: image
init_img_path: ./data/panorama/panorama_low_res.png

#===============================================================================
# Prior
#===============================================================================
prior: sd
guidance_scale: 7.5
mixed_precision: true

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: linear_annealing 
t_max: 600
t_min: 270

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: sds

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1