root_dir: ./results/
tag: stochsync_sphere
text_prompt: "A sweet candy texture"

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 12
warmup_steps: 1

use_ode: true
ode_steps: 25
seam_removal_steps: 4

use_closed_form: true
recon_type: rgb
recon_steps: 1

disable_debug: False
try_fast_sampling: True

#===============================================================================
# Dataset
#===============================================================================
dataset: quat
height: 512
width: 512
batch_size: 6
fov: 90
dists: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
elevs: [0, 0, 0, 0, 90, -90]
azims: [0, 90, 180, 270, 0, 0]

#===============================================================================
# Background
#===============================================================================
background: solid
rgb: [0, 0, 0]

#===============================================================================
# Model
#===============================================================================
model: panorama
mode: sphere
pano_height: 2048
pano_width: 4096
channels: 3
seam_removal_mode: both

#===============================================================================
# Prior
#===============================================================================
prior: sd
guidance_scale: 8.5
mixed_precision: True

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: linear_annealing 
t_max: 999
t_min: 400

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: sds

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 1