root_dir: ./results
tag: tall_image
text_prompt: "A bird's eye view of an alley with shops"

#===============================================================================
# Trainer settings
#===============================================================================
max_steps: 50
warmup_steps: 0

use_ode: false
ode_steps: -1
seam_removal_steps: 0

use_closed_form: true
recon_type: latent
recon_steps: 1

disable_debug: False

#===============================================================================
# Dataset
#===============================================================================
dataset: image_wide
batch_size: 15
height: 64
width: 64
xscale: 1
yscale: 4

#===============================================================================
# Background
#===============================================================================
background: solid
rgb: [0, 0, 0, 0]

#===============================================================================
# Model
#===============================================================================
model: image_wide
channels: 4

#===============================================================================
# Prior
#===============================================================================
prior: sd
guidance_scale: 7.5
mixed_precision: True

#===============================================================================
# Time sampler
#===============================================================================
time_sampler: linear_annealing 
t_max: 999
t_min: 0

#===============================================================================
# Noise sampler
#===============================================================================
noise_sampler: ddim
get_noise_from_model: True

#===============================================================================
# Logger
#===============================================================================
logger: self
log_interval: 5