root_dir: "./mesh_final_exp3/tmp14"
tag: mesh
text_prompt: "A DSLR photo of a 3D dragon"
max_steps: 30
batch_size: 10

dataset: camera
height: 96
width: 96
convention: OpenGL
up_vec: y
fov: 60
dists: [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]
elevs: [0, 0, 0, 0, 0, 0, 0, 0, 30, 30]
azims: [0, 45, 90, 135, 180, 225, 270, 315, 0, 180]


background: solid
rgb: [0.25, 0.25, 0.25, 0.25]

model: mesh
mesh_path: "/home/aaaaa/data/texgen/processed/dragon.obj"
texture_size: 2048
mesh_scale: 1.0
initialization: gray
learning_rate: 0.05
disable_debug: False # Faster 
channels: 4
sampling_mode: linear-mipmap-linear

prior: controlnet
guidance_scale: 15.5
mixed_precision: true

time_sampler: linear_annealing 
t_max: 999 # In Tweedie -> 999
t_min: 0 # In Tweedie -> 0
noise_sampler: ddim

use_ode: false
ode_steps: 75
seam_removal_steps: 0

logger: simple_latent
log_interval: 1

recon_steps: 1
recon_type: latent
use_closed_form: true
use_selection: false