root_dir: "./results/mesh"
tag: mesh
text_prompt: "a DSLR photo of a kratos, the god of war, realistic"
max_steps: 30
batch_size: 3

dataset: random_mv
height: 512
width: 512
convention: OpenGL
up_vec: y
fov: 60
dist_range: [2.3, 2.5]
asim_range: [0, 360]
elev_range: [-15, 60]


background: solid
rgb: [0.25, 0.25, 0.25]

model: mesh
mesh_path: "face.obj"
texture_size: 2048
mesh_scale: 1.0
initialization: gray
learning_rate: 0.05
disable_debug: False # Faster 

prior: controlnet
guidance_scale: 15.5

time_sampler: linear_annealing 
t_max: 900 # In Tweedie -> 999
t_min: 270 # In Tweedie -> 0
noise_sampler: sds

use_ode: true
ode_steps: 75
seam_removal_steps: 10

logger: self 
log_interval: 1

recon_steps: 1
recon_type: rgb
use_closed_form: true
use_selection: true