root_dir: "./viewer/tmp15"
tag: mesh
text_prompt: "A DSLR photo of a 3D dragon"
num_cameras: 1

dataset: camera
height: 768
width: 768
convention: OpenGL
up_vec: y
fov: 60
dists: [
  2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0,
]
elevs: [
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
]
azims: [
  0, 36, 72, 108, 144, 180, 216, 252, 288, 324,
]

background: solid
rgb: [1.0, 1.0, 1.0]

model: mesh
mesh_path: "/home/aaaaa/data/texgen/processed/8a60954eccad433e987bbcafc7657140.obj"
texture_size: 2048
mesh_scale: 1.0
initialization: image
texture_path: "/home/aaaaa/data/texgen/mvedit/8a60954eccad433e987bbcafc7657140_A_Japanese_armor.png"
learning_rate: 0.05
disable_debug: False # Faster 
channels: 3
sampling_mode: nearest

prior: controlnet
guidance_scale: 15.5
mixed_precision: true

logger: simple
log_interval: 1
save_type: images