root_dir: "./results/latent_mesh_sd"
text_prompt: "a DSLR photo of face of a handsome guy, best quality, high quality, extremely detailed, good geometry"
max_steps: 1000
batch_size: 4

dataset: random
height: 64
width: 64
convention: OpenGL
up_vec: y
#dist_range: [2.8, 3.0]
#elev_range: [-10, 30]
dist_range: [3.0, 3.0]
# elev_range: [15, 15]
# azim_range: [0, 0]
fov: 45

background: latent_solid
rgb: [0.25, 0.25, 0.25]

model: mesh
mesh_path: "face.obj"
texture_size: 512
channels: 4
mesh_scale: 1.0
initialization: "random"
learning_rate: 0.01
decay:  0
lr_decay:  0.9
decay_step: 100
lr_plateau: false

prior: sd
# guidance_scale: 7.5
guidance_scale: 35.5

sampler: sds
linear_annealing: true

logger: simple_latent
log_interval: 10