root_dir: "./results/mesh_sd_bird"
text_prompt: "a DSLR photo of face of a handsome guy, best quality, high quality, extremely detailed, good geometry"
max_steps: 1000
batch_size: 4

dataset: random
height: 512
width: 512
convention: OpenGL
up_vec: y
dist_range: [2.8, 3.0]
elev_range: [-10, 30]
fov: 45

background: solid
rgb: [0.25, 0.25, 0.25]

model: paintit_mesh
mesh_path: "face.obj"
texture_size: 512
mesh_scale: 1.0
sampling_mode: "bilinear"
initialization: "gray"
learning_rate: 0.0005
decay:  0
lr_decay:  0.9
decay_step: 100
lr_plateau: false

prior: sd
guidance_scale: 7.5

sampler: sdi

logger: procedure
log_interval: 10