root_dir: "./results/mesh_render"
dataset: random
convention: Pytorch3D
background: solid
model: latent_mesh
prior: sd
sampler: sds
linear_annealing: true
logger: simple_latent
height: 64
width: 64

mesh_path: "tmp_mesh.obj"
texture_size: 1024
mesh_scale: 1.0
sampling_mode: "nearest"