root_dir: "./results/mesh_controlnet"
tag: mesh
text_prompt: "a DSLR photo of face of Kratos, god of war, best quality, high quality, extremely detailed, good geometry"
max_steps: 800
batch_size: 2

dataset: random
height: 512
width: 512
convention: OpenGL
up_vec: y
dist_range: [2.8, 3.0]
elev_range: [-10, 30]
fov: 45

background: solid
rgb: [0.25, 0.25, 0.25]

model: mesh
mesh_path: "/home/aaaaa/repo/distill/_previous_results_bin/extra_data/face.obj"
texture_size: 1024
mesh_scale: 1.0
initialization: "random"
learning_rate: 0.05
decay:  0
lr_decay:  0.9
decay_step: 100
lr_plateau: false

prior: controlnet
guidance_scale: 15.5

time_sampler: linear_annealing
noise_sampler: sds

use_ode: false
ode_steps: 100

logger: self 
log_interval: 20

recon_steps: 1
recon_type: latent  # optim=1: latent, optim=inf: rgb
use_closed_form: false